# Generated by Django 2.1.3 on 2018-11-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userregistration', '0001_initial'),
        ('events', '0003_auto_20181130_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationsSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('accepted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userregistration.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='invitations',
            name='event',
        ),
        migrations.RemoveField(
            model_name='invitations',
            name='organizer',
        ),
        migrations.DeleteModel(
            name='Invitations',
        ),
    ]
